name: Deploy to ECR

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: wiz
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1
    
    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v2
    
    - name: Build and push Docker image
      env:
        ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        ECR_REPOSITORY: todoapp
      run: |
        TIMESTAMP=$(date +%Y%m%d-%H%M%S)
        docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$TIMESTAMP .
        docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:latest .
        docker push $ECR_REGISTRY/$ECR_REPOSITORY:$TIMESTAMP
        docker push $ECR_REGISTRY/$ECR_REPOSITORY:latest
        echo "IMAGE_TAG=$TIMESTAMP" >> $GITHUB_ENV
        echo "ECR_REGISTRY=$ECR_REGISTRY" >> $GITHUB_ENV
    
    - name: Update EKS kubeconfig
      run: |
        aws eks update-kubeconfig --region us-east-1 --name wiz-cluster
    
    - name: Update Kubernetes deployment
      run: |
        kubectl set image deployment/todoapp todoapp=${{ env.ECR_REGISTRY }}/todoapp:${{ env.IMAGE_TAG }}
        kubectl rollout status deployment/todoapp
